### ISSUE TITLE
Print screenshot with single frequency characteristics

### ISSUE THREAD

**Issue by tomverbeure** [VK2BEA/HP8753-Companion#12]
Right now, when you move the mouse on the Smith chart, it will show the characteristics for that particular frequency, but it's not possible to export that as a screenshot file: the moment you move the mouse away, the characteristics disappear.

![smith_chart_parameters](https://github.com/VK2BEA/HP8753-Companion/assets/36720790/94aef97c-7672-4ade-9049-49ff28d7c8ee)

It would be great if there were a way to print that.

Tom

**Comment by VK2BEA** [comment]
OK Tom, I've made a change so that if you now press the middle mouse button when there is a live marker, it's position is frozen. 
If is freed when a new trace retrieved (from the 8753 or disk), or you can press the left or right mouse button (when in the display) to unfreeze.

**Comment by tomverbeure** [comment]
Fantastic!
Thanks!
Tom
