### ISSUE TITLE
"GPIB-Linux.driver" dkms.conf calls old version

### ISSUE THREAD

**Issue by Skroder** [VK2BEA/HP8753-Companion#4]
In the version 1.19.1 of HP8753-Companion the folder "GPIB-Linux.driver" has the dkms.conf set to:
PACKAGE_NAME="linux-gpib"
PACKAGE_VERSION="4.3.4"
AUTOINSTALL=yes

Should the PACKAGE_VERSION now be "4.3.6" ?

**Comment by VK2BEA** [comment]
Yes, thanks for letting me know!

**Comment by Skroder** [comment]
Fixed.
