### ISSUE TITLE
Issue on RPI

### ISSUE THREAD

**Issue by cvell** [VK2BEA/HP8753-Companion#8]
Hi,
I installed the libgpib with success and validate test (ibtest) with a 8753ES connected with ni usb hs device.
8753-companion was build ans installed with success, despite the fact that an error regarding unsigned long showed up and I replace it with the %ull in a printf directive to fix the error (it concern HP8753comms.c):
```
 g_string_append_printf( stCalKit, "OFSD %.17le; OFSL %.17e; OFSZ %lg; MINF %lu; MAXF %lu; %s; STDD; ",
                    pStandard->offsetDelay, pStandard->offsetLoss, pStandard->offsetZ0,
                    pStandard->minFreqHz, pStandard->maxFreqHz,
                    pStandard->connectorType == eConnectorTypeCoaxial ? "COAX" : "WAVE");
```
=> %lu replaced by %llu to fix the error.
Then installation goes well.

But when executing the companion I got following issues while trying getting trace ( and the app finally crash):
Here's the journal after  a --debug 7 when loading the app.

chris@raspberrypi:~ $ journalctl -t hp8753 -f
-- Journal begins at Tue 2023-02-21 03:02:30 CET. --
mars 14 10:51:30 raspberrypi hp8753[1760]: Cannot query identity - cannot proceed
mars 14 10:51:43 raspberrypi hp8753[1760]: Ending
mars 14 10:53:50 raspberrypi hp8753[2185]: Starting
mars 14 10:53:50 raspberrypi hp8753[2185]: Linux raspberrypi 6.1.21-v7l+ #1642 SMP Mon Apr  3 17:22:30 BST 2023 armv7l
mars 14 10:53:50 raspberrypi hp8753[2185]: HP8753 Companion version: v1.28.3
mars 14 10:54:04 raspberrypi hp8753[2185]: 🖊 HP8753: IDN?;
mars 14 10:54:04 raspberrypi hp8753[2185]: 🖊 HP8753: 5 / 5 bytes
mars 14 10:54:04 raspberrypi hp8753[2185]: 👓 HP8753: 40 bytes (50 max)
mars 14 10:54:04 raspberrypi hp8753[2185]: IDN returns "HEWLETT PACKARD,8753ES,US39172545,7.74 
                                           "
mars 14 10:54:04 raspberrypi hp8753[2185]: Cannot query identity - cannot proceed

After startup I need to configure manually the GPIB number 16 to get the "contat established" mention at the bottom left on the window. 
As soon as I push "Get Trace" button, it show up:"Cannot query identity- cannot proceed", a second press will crash the app.

It's installed on a PI400:
`Linux raspberrypi 6.1.21-v7l+ #1642 SMP Mon Apr  3 17:22:30 BST 2023 armv7l GNU/Linux`
Sincerely,

**Comment by VK2BEA** [comment]
OK, I was assuming a purely numeric S/N when parsing the IDN? string.
I've fixed that now. Please pull the changes and try again.
(Thanks for reporting the issue.... with each new model tried there are always a few issues.)_

**Comment by cvell** [comment]
I did the re-installation but I got the same issue:
```
chris@raspberrypi:~/8753-comp/HP8753-Companion/build $ journalctl -t hp8753 -f
-- Journal begins at Tue 2023-02-21 03:02:30 CET. --
mars 15 11:20:58 raspberrypi hp8753[8837]: Cannot query identity - cannot proceed
mars 15 11:21:18 raspberrypi hp8753[8837]: Ending
mars 15 11:21:33 raspberrypi hp8753[8869]: Starting
mars 15 11:21:33 raspberrypi hp8753[8869]: Linux raspberrypi 6.1.21-v7l+ #1642 SMP Mon Apr  3 17:22:30 BST 2023 armv7l
mars 15 11:21:33 raspberrypi hp8753[8869]: HP8753 Companion version: v1.29.1
mars 15 11:21:36 raspberrypi hp8753[8869]: 🖊 HP8753: IDN?;
mars 15 11:21:36 raspberrypi hp8753[8869]: 🖊 HP8753: 5 / 5 bytes
mars 15 11:21:36 raspberrypi hp8753[8869]: 👓 HP8753: 40 bytes (50 max)
mars 15 11:21:36 raspberrypi hp8753[8869]: IDN returns "HEWLETT PACKARD,8753ES,US39172545,7.74 
                                           "
mars 15 11:21:36 raspberrypi hp8753[8869]: Cannot query identity - cannot proceed
```

**Comment by VK2BEA** [comment]
Can you look at the code an make sure this line in `HP8753comms.c`  is as shown ..
https://github.com/VK2BEA/HP8753-Companion/blob/21e4430b0f65aec4f4c12cae80b2259a4161bd9e/src/HP8753comms.c#L510

**Comment by cvell** [comment]
Here's the source code I cloned from GIT (and installed):
`nConv = sscanf( ASCIIanswer, "%50[^,],%50[^,],%50[^,],%d.%d", sManufacturer, sProduct, sSerial, &ver, &rev );`
It's the same.

**Comment by VK2BEA** [comment]
OK, thanks for double checking. 
I see I introduced a problem when I changed that line and now do 5 conversions rather than 4 (which is checked a few lines below). I've updated again, please check with the new version.

**Comment by cvell** [comment]
Hi,
it works well now!
Working with 4 parameters view, a get trace ill displays S11 and S21.
Is there a trick to display S12 and S22?
Sincerely,

**Comment by VK2BEA** [comment]
So with the ES, you can get 4 traces at the same time?   Nice ... 
It would not be to difficult for me to modify (adding two more channels) but I have no way to test it.
I guess the HPGL plot shows them.
